### ISSUE TITLE
Support empty request payloads for generic entity API

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#303] opened 2020-06-17 12:27 UTC
For entity types that are configured in the database with `{..., :named? false}`, allow omitting the payload `data`.
For all endpoints, allow provenance to be omitted as defaults are populated dynamically by the API.
i.e currently, callers are required to pass empty maps for the `prov` and `data` parameters to endpoints when there are no required key/values, e.g:
```
# Killing a gene requires no entries in`data`, nor provenance 
curl -H "Authorization: Token $TOKEN" -H "Content-type: application/json" \
         -X DELETE \ 
         -d "prov={}" -d "data={}" \
        "https://test-names/api/gene/ced-7"
```

**Comment by mluypaert** [comment] 2021-04-13 10:50
Unclear what this would solve as there are no currently reported issues caused by this. Closing the ticket.

**Closed as completed by mluypaert** 2021-04-13 10:50 UTC
Labels: enhancement
